# Path: src/shared/utilities/constants.py
from enum import Enum

# Log levels
class LogLevel(Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

# Supported languages
class Language(Enum):
    FA = "fa"
    EN = "en"

# HTTP status codes
class HttpStatus(Enum):
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404
    CONFLICT = 409
    TOO_MANY_REQUESTS = 429
    INTERNAL_SERVER_ERROR = 500
    SERVICE_UNAVAILABLE = 503

# Error types (from handlers.py)
class ErrorType(Enum):
    GENERAL = "general"
    DATABASE = "database"
    SERVICE = "service"
    AUTHENTICATION = "authentication"

# Domain error codes
class DomainErrorCode(Enum):
    # Application
    LIFESPAN_ERROR = "LIFESPAN_ERROR"

    # Token
    TOKEN_GENERATION_FAILED = "TOKEN_GENERATION_FAILED"
    TOKEN_REVOCATION_FAILED = "TOKEN_REVOCATION_FAILED"
    TOKEN_TYPE_MISMATCH = "TOKEN_TYPE_MISMATCH"
    MISSING_JTI = "MISSING_JTI"
    INVALID_TOKEN_PAYLOAD = "INVALID_TOKEN_PAYLOAD"
    TOKEN_DECODE_FAILED = "TOKEN_DECODE_FAILED"
    INVALID_TOKEN_PROFILE = "INVALID_TOKEN_PROFILE"
    INVALID_TOKEN_TYPE = "INVALID_TOKEN_TYPE"

    # Admin Setup
    MISSING_ADMIN_USERNAME = "MISSING_ADMIN_USERNAME"
    MISSING_ADMIN_PASSWORD = "MISSING_ADMIN_PASSWORD"
    INVALID_ADMIN_PASSWORD = "INVALID_ADMIN_PASSWORD"

    # Catalog
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
    INVALID_PRODUCT_DATA = "INVALID_PRODUCT_DATA"

    # Payment
    INVALID_PAYMENT = "INVALID_PAYMENT"
    PAYMENT_DECLINED = "PAYMENT_DECLINED"
    PAYMENT_TIMEOUT = "PAYMENT_TIMEOUT"

    # Order
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_LIMIT_EXCEEDED = "ORDER_LIMIT_EXCEEDED"
    INVALID_ORDER = "INVALID_ORDER"

    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"

    # Authentication
    OTP_EXPIRED = "OTP_EXPIRED"
    OTP_INVALID = "OTP_INVALID"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_INPUT = "INVALID_INPUT"
    UNSUPPORTED_CHANNEL = "UNSUPPORTED_CHANNEL"
    NOTIFICATION_DISPATCH_FAILED = "NOTIFICATION_DISPATCH_FAILED"

    # Access Control
    PERMISSION_DENIED = "PERMISSION_DENIED"

    # Notification
    NOTIFICATION_FAILED = "NOTIFICATION_FAILED"

    # Security
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY"
    DEVICE_MISMATCH = "DEVICE_MISMATCH"
    DEVICE_FINGERPRINT_FAILED = "DEVICE_FINGERPRINT_FAILED"

    # Service
    NO_RESULT = "NO_RESULT"
    INVALID_RESULT = "INVALID_RESULT"

    # Validation
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Permissions
    INVALID_PERMISSION_DATA = "INVALID_PERMISSION_DATA"

    # Session
    INVALID_SESSION_DATA = "INVALID_SESSION_DATA"

    # Profile
    INVALID_CATEGORY = "INVALID_CATEGORY"
    INELIGIBLE_PROFILE = "INELIGIBLE_PROFILE"
    MISSING_FIELDS = "MISSING_FIELDS"
    INVALID_VISIBILITY = "INVALID_VISIBILITY"
    INVALID_VENDOR_TYPE = "INVALID_VENDOR_TYPE"
    UPDATE_FAILED = "UPDATE_FAILED"

    # Permissions loading
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    INVALID_PERMISSIONS_FORMAT = "INVALID_PERMISSIONS_FORMAT"
    INVALID_PERMISSIONS_YAML = "INVALID_PERMISSIONS_YAML"
    PERMISSIONS_LOAD_FAILED = "PERMISSIONS_LOAD_FAILED"

    # Sentry
    SENTRY_INIT_FAILED = "SENTRY_INIT_FAILED"

# Infrastructure error codes
class InfraErrorCode(Enum):
    DATABASE_CONNECTION = "DATABASE_CONNECTION_FAILED"
    QUERY_TIMEOUT = "QUERY_TIMEOUT"
    CACHE_ERROR = "CACHE_ERROR"
    MONGO_ERROR = "MONGO_ERROR"
    PAYMENT_GATEWAY = "PAYMENT_GATEWAY"
    SMS_SERVICE = "SMS_SERVICE"
    EMAIL_SERVICE = "EMAIL_SERVICE"
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    CONNECTION_ERROR = "CONNECTION_ERROR"